### ISSUE TITLE
Missing .lib file

### ISSUE THREAD

**Issue by sheepfly** [LittleNate-Dev/RenderBoy#1]
I couldn't run the code.
The output is [ LINK : fatal error LNK1104: 无法打开文件“assimp-vc143-mt.lib” ]
This is a dependency that is generated or imported.

**Comment by LittleNate-Dev** [comment]
I forgot to upload bin folder in ./RenderBoy/data so some .lib and .dll files are missing. Download latest version and LINK problem should be gone.
